# https://docs.ansible.com/ansible/2.5/modules/docker_container_module.html
---
- hosts: web
  become: true
  vars:
    default_container_name: web
    default_container_image: nginx:alpine
    default_container_command: sleep 1d

  tasks:
    - name: Install Python dependencies CentOS
      yum:
        name: [python3-pip, python3-devel]
        state: latest
      when: ansible_os_family in ["CentOS","RedHat"]


    - name: "Install Python pip UBUNTU"
      apt:
        name: [python3-pip]
        state: latest
      when: ansible_os_family == "Debian"


    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull Nginx Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create Nginx container
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: started 
        recreate: yes
        exposed_ports:
          - "80"


    - name: Start Nginx container
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        state: started 
        ports:
          - "0.0.0.0:8080:80"