- hosts: db
  become: yes
  tasks:
    - name: "apt-get update"
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: "Install Python pip"
      apt:
        name: [python3-pip]
        state: latest

    - name: "Make sure pymysql is present"
      pip:
        name: pymysql
        state: present

    - name: "Install Mysql"
      apt:
        name: [python-mysqldb, mysql-server, mysql-client]
        state: latest

    - name: Start the MySQL service
      action: service name=mysql state=started
 
    - name: update mysql root password for all root accounts
      mysql_user: 
        name: root 
        host: "{{ item }}" 
        password: "{{ mysql_root_password }}" 
        priv: "*.*:ALL,GRANT"
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost 