- hosts: db
  become: yes
  tasks:
  - name: "apt-get update"
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: "Install Python pip"
    apt:
      name: [python3-pip]
      state: latest

  - name: "Install Mysql"
    apt:
      name: [python-mysqldb, mysql-server, mysql-client]
      state: latest


  - name: Start the MySQL service
    action: service name=mysql state=started

  - name: Set MySQL root Password
    mysql_user:
      login_host: 'localhost'
      login_user: 'root'
      login_password: ''
      name: 'root'
      password: '{{ mysql_root_password }}'
      state: present

