- hosts: db
  become: yes
  tasks:
    - name: "apt-get update"
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: "Install Python pip"
      apt:
        name: [python3-pip]
        state: latest

    - name: "Make sure pymysql is present"
      pip:
        name: pymysql
        state: present

    - name: "Install Mysql"
      apt:
        name: [python-mysqldb, mysql-server, mysql-client]
        state: latest

    - name: Start the MySQL service
      action: service name=mysql state=started
 
    - name: Create deploy user for Mysql
      mysql_user: user="firas" host="%" password={{mysql_root_password}} priv=*.*:ALL,GRANT
    
    - name: copy .my.cnf file with root password credentials
      template: src=templates/.my.cnf dest=/etc/mysql/my.cnf owner=root mode=0600

    - name: update mysql root password for all root accounts
      mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: delete anonymous MySQL server user for $server_hostname
      action: mysql_user user="" host="{{ server_hostname }}" state="absent"

    - name: delete anonymous MySQL server user for localhost
      action: mysql_user user="" state="absent"

    - name: remove the MySQL test database
      action: mysql_db db=test state=absent