# https://docs.ansible.com/ansible/2.5/modules/docker_container_module.html
---
- hosts: web
  become: true
  vars:
    default_container_name: web
    default_container_image: nginx:alpine

  tasks:
    - name: Pull Nginx Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create Nginx container
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        state: started 
        exposed_ports:
          - "80"

    - name: Start Nginx container
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        state: started 
        ports:
          - "0.0.0.0:8080:80"