---
- hosts: web
  become: true
  vars:
    letsencrypt_email: me@firas-chbiki.com
    
  tasks:        
    - name: Install Python simplejson
      apt:
        pkg: python-simplejson
        state: present
        update_cache: true
    
    - name: install letsencrypt
      apt:
        name: letsencrypt
        state: latest
    
    - name: create letsencrypt directory
      file:
        name: /var/www/letsencrypt
        state: directory
    
    - name: Remove default nginx config
      file:
        name: /etc/nginx/sites-enabled/default
        state: absent
 
    - name: Install nginx site for letsencrypt requests
      template:
        src: templates/nginx-http.j2
        dest: /etc/nginx/sites-enabled/http
    
    - name: Reload nginx to activate letsencrypt site
      service:
        name: nginx
        state: restarted
    
    - name: Create letsencrypt certificate
      shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain }}
      args:
        creates: /etc/letsencrypt/live/{{ domain }}
    
    - name: Generate dhparams
      shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
      args:
        creates: /etc/nginx/dhparams.pem
    
    - name: Add empty data directory for {{ domain }} static files at /var/www/{{ domain }}
      become: true
      file:
        path: "/var/www/{{ domain }}"
        state: directory
        mode: u=rwx,g=r,o=r
        owner: www-data
        group: www-data
    
    - name: Install nginx site for {{ domain }}
      template:
        src: templates/site-secured.j2
        dest: /etc/nginx/sites-enabled/{{ domain }}
    
    - name: Reload nginx to activate specified site
      service:
        name: nginx
        state: restarted
    
    - name: Add letsencrypt cronjob for cert renewal
      cron:
        name: letsencrypt_renewal
        special_time: weekly
        job: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos-d {{ domain }} && service nginx reload
    