- hosts: web
  become: yes
  tasks:
  - name: "Update packages list Ubuntu"
    apt:
      update_cache: yes
      cache_valid_time: 3600
    when: ansible_os_family == "Debian"

  - name: "Install nginx Ubuntu"
    apt:
      name: ['nginx']
      state: latest
    when: ansible_os_family == "Debian"

  - name: "Install nginx CentOS"
    yum:
      name: ['nginx']
      state: latest
    when: ansible_os_family in ["CentOS","RedHat"]

  - name: "Create www directory"
    file:
      path: /var/www/{{ domain }}
      state: directory
      mode: '0775'
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

  - name: Delete default nginx conf file
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: restart nginx

  - name: Copy nginx custom conf file
    template:
      src: templates/site-not-secure.conf.j2
      dest: /etc/nginx/sites-enabled/{{ domain }}
      owner: root
      group: root
      mode: '0644'
    notify: restart nginx

  - name: Add website source code
    synchronize:
      src: site/
      dest: /var/www/{{ domain }}
      archive: no
      checksum: yes
      recursive: yes
      delete: yes
    notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted