---
- hosts: web
  become: true
  vars:
    letsencrypt_email: me@firas-chbiki.com
    
  tasks:        
    - name: Install Python simplejson
      apt:
        name: python-simplejson
        state: present
    
    - name: Install letsencrypt
      apt:
        name: letsencrypt
        state: latest
    
    - name: Create letsencrypt directory
      file:
        name: /var/www/letsencrypt
        state: directory
    
    - name: Install nginx config for letsencrypt requests
      template:
        src: templates/nginx-http.j2
        dest: /etc/nginx/sites-enabled/http
      notify: restart nginx
      
    - name: Create letsencrypt certificate
      shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain }}

    - name: Generate dhparams
      shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
    
    - name: Install nginx site for {{ domain }}
      template:
        src: templates/site-secured.j2
        dest: /etc/nginx/sites-enabled/{{ domain }}
      notify: restart nginx
    
    - name: Add letsencrypt cronjob for cert renewal
      cron:
        name: letsencrypt_renewal
        special_time: weekly
        job: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos-d {{ domain }} && service nginx reload
    
    handlers:
      - name: restart nginx
        service:
          name: nginx
          state: restarted